### ISSUE TITLE
Backup Path

### ISSUE THREAD

**Issue by julmarfur** [renderpci/dedalo-4#11]
Hello, I'm a new user from Valencia, and when I'm restoring the DB I write /install/db/dedalo4_install.backup

I don't know why but it doesn't work. I hope you can help me. Thanks.

**Comment by renderpci** [comment]
Hi julmarfur

Thanks for download and try to install Dédalo.

For help you, can put the command that you are using for restore?

**Comment by julmarfur** [comment]
pg_restore -dpU --username=postgres --port:5432 --dbname=dedalo_heisenberg install/db/dedalo4_install.backup

**Comment by renderpci** [comment]
With this command you will get many errors because the restore database is not CLEAN.

Please read the pg_restore command in postgreSQL
https://www.postgresql.org/docs/current/static/app-pgrestore.html

and for restore you need install the database with the "clean" option:

"-c
--clean
Clean (drop) database objects before recreating them. (Unless --if-exists is used, this might generate some harmless error messages, if any objects were not present in the destination database.)
"

**Comment by renderpci** [comment]
It works?

**Comment by julmarfur** [comment]
It works! Thank You!

**Comment by julmarfur** [comment]
What do you mean by /var/pgsql-socket/?

**Comment by renderpci** [comment]
Perfect!
