### ISSUE TITLE
"Informants" Tool slow 

### ISSUE THREAD

**Issue by cpagenstecher** [renderpci/dedalo-4#13]
This tool currently is very slow for Damian and Anna Maria. It works for me. But it stops Damian, even when I made him Administrator. His other internet works. He uses Chrome.

**Comment by renderpci** [comment]
where did it happen?

In: Inventory->Oral History-> Informants
![screen shot 2017-03-23 at 15 14 40](https://cloud.githubusercontent.com/assets/8447635/24251746/8082ce5a-0fdb-11e7-8127-f581940733df.png)

![screen shot 2017-03-23 at 15 14 49](https://cloud.githubusercontent.com/assets/8447635/24251755/86b945c4-0fdb-11e7-8510-8c3bac579489.png)

Or in; Resources-> informants ?

![screen shot 2017-03-23 at 15 13 06](https://cloud.githubusercontent.com/assets/8447635/24251686/4de34434-0fdb-11e7-859a-2f1b07e45248.png)

**Comment by cpagenstecher** [comment]
I think, when they go from Resources > Informants, it slows down, and then even other functions are slow.

**Comment by renderpci** [comment]
Ok, I go to see the log...

**Comment by renderpci** [comment]
We find the error. The problem was a term in a Greece toponymy : 
Sitarálona
that parent point to himself: 
Thermo -> Thermo

do a infinite loop in the "place of born" field of informants:
Sitarálona ->Thermo -> Thermo -> Thermo -> etc

The error was in the 12 informant and you can't see the error because you informant list is full, with all informants, and Damian and Anna María only can see the Greece project. In other words; you see the 1-10 first informants in the main list, but their see 10-28 in the main list.

The problem affect to all new toponymy of geonames, it have lots of errors that we intent fix, but is a lot of work and we can't review all. Lasts weeks we was working to do some scripts to clean the most obvious errors but is hard detect it because all hierarchies have about 800.000 terms.

We think that now the toponymy of geonames is "usable" but is far to be "good" or "perfect".

Please if you see other error, comment it. :-)

**Comment by renderpci** [comment]
One more thing:

For prevent similar errors, we change the recursive resolution of parents in the fields that call to toponymy to only 1.

Now only will see only the first parent of the term. 

before:
Benimàmet-Beniferri-> Valencia-> l'horta nord-> Valencia - Comunitat Valenciana-> España
now:
Benimamet -> Valencia

This change is a temporary change for prevent the errors in toponymy, and will go to normal resolution when the new geonames toponymy can be more "stable" or "revised"
